Optimized: main.cpp
	g++ -O3 -std=c++2a -fsanitize=address main.cpp -o optimized
NonOptimized: main.cpp
	g++ -std=c++2a -fsanitize=address main.cpp -o nonoptimized
clean:
	rm optimized
	rm nonoptimized
